image: Ubuntu2004
stack: jdk 11

environment:
  JAVA_TOOL_OPTIONS: "-Dhttps.protocols=TLSv1.2"

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-mbank.jar &
  - chmod +x gradlew
  - |
    echo "Waiting for SUT on http://localhost:9999 ..."
    for i in {1..30}; do
      if curl -sSf http://localhost:9999/api/demo > /dev/null || \
         curl -sSf http://localhost:9999/api/v1/demo/accounts > /dev/null; then
        echo "SUT is UP"
        break
      else
        echo "Not ready yet ($i)"
        sleep 2
      fi
    done

build_script:
  - ./gradlew --version

  - ./gradlew test --no-daemon --refresh-dependencies --stacktrace --info || (
    echo "Retry #1 in 5s" && sleep 5 &&
    ./gradlew test --no-daemon --refresh-dependencies --stacktrace --info
    ) || (
    echo "Retry #2 in 10s" && sleep 10 &&
    ./gradlew test --no-daemon --refresh-dependencies --stacktrace --info
    )